# This file defines services you want available to your application.

elasticsearch:
    type: elasticsearch:5.4
    disk: 256
    size: S
influxdb:
    type: influxdb:1.3
    disk: 256
    size: S
memcached:
    type: memcached:1.4
    size: S
mongodb:
    type: mongodb:3.6
    disk: 512
    size: S
mysql:
    type: mysql:10.2
    disk: 256
    size: S
postgresql:
    type: postgresql:11
    disk: 256
    size: S
redis:
    type: redis:5.0
    size: S
rabbitmq:
    type: rabbitmq:3.5
    disk: 256
    size: S
solr:
    type: solr:6.6
    disk: 256
    size: S
